insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'nFabeO.png', '[?25lhttps://www.france-export-fv.com/Barquettes-Lu-Fraises/en')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'BDopnk.jpg', '[?25lhttps://drhmarket.fr/en/viennoiseries/58553-belle-france-barquettes-chocolat120bf-3258561020563.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'GGnOfL.jpg', 'https://www.france-export-fv.com/Barquettes-Lu-Fraises/en')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'BcDCHi.jpg', 'https://www.france-export-fv.com/Barquettes-Lu-Fraises/en')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'DMHDfd.jpg', 'https://drhmarket.fr/en/viennoiseries/58553-belle-france-barquettes-chocolat120bf-3258561020563.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'LFJpLJ.png', 'https://www.france-export-fv.com/Barquettes-Lu-Fraises/en')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'gfGfBM.jpg', 'https://drhmarket.fr/en/viennoiseries/58553-belle-france-barquettes-chocolat120bf-3258561020563.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'iNfAKo.jpg', 'https://www.france-export-fv.com/Barquettes-Lu-Fraises/en')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'kPhgce.jpg', 'https://drhmarket.fr/en/viennoiseries/58553-belle-france-barquettes-chocolat120bf-3258561020563.html')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'dFPBEA.jpg', '[?25lhttps://world-nb.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'mnadeF.jpg', '[?25lhttps://biscuitsetcompagnie.com/13-produits-regionaux')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'NHkNoJ.png', 'https://www.collinsdictionary.com/dictionary/french-english/barquette')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'mBdnLf.png', 'https://biscuitsetcompagnie.com/13-produits-regionaux')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'OAEifl.png', 'https://www.collinsdictionary.com/dictionary/french-english/barquette')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'kDDBEp.jpg', 'https://biscuitsetcompagnie.com/13-produits-regionaux')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'CBmnNF.png', 'https://biscuitsetcompagnie.com/13-produits-regionaux')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'KoFkHJ.jpg', 'https://snippetsofparis.com/french-gouter/')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'laAPNa.jpg', 'https://drhmarket.fr/en/viennoiseries/58553-belle-france-barquettes-chocolat120bf-3258561020563.html')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'cbFjja.jpg', 'https://biscuitsetcompagnie.com/13-produits-regionaux')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'CkfPIG.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1043-mini-gouter-rond-chocolat-168g-belle-france-3258561020815.html')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'jNOGmc.jpg', 'https://www.biscuiterie-de-kerlann.com/boutique-en-ligne/')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'hcMIBe.jpg', 'https://www.collinsdictionary.com/dictionary/french-english/barquette')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'BEoKFh.png', 'https://www.biscuiterie-de-kerlann.com/boutique-en-ligne/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'jHmfif.jpg', 'https://world-nb.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'hCgLcA.jpg', 'https://www.collinsdictionary.com/dictionary/french-english/barquette')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'jodkCh.png', 'https://cadismarket.com/en/biscuits-gateaux/1043-mini-gouter-rond-chocolat-168g-belle-france-3258561020815.html')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'pPnfNB.png', 'https://www.lepetitdepot.com/en/catalog/sweet-groceries/pocket-biscuits/belle-france-chocolate-barquette-120g')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'CnkKaD.svg', 'https://www.collinsdictionary.com/dictionary/french-english/barquette')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'FhFAJK.jpg', 'https://www.biscuiterie-de-kerlann.com/boutique-en-ligne/')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'nJjBAj.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1043-mini-gouter-rond-chocolat-168g-belle-france-3258561020815.html')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'HCaFOm.jpg', 'https://world-nb.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'mcgKah.png', 'https://www.lepetitdepot.com/en/catalog/sweet-groceries/pocket-biscuits/belle-france-chocolate-barquette-120g')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'cajHlA.jpg', 'https://world-nb.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'DhjIJM.png', 'https://www.biscuiterie-de-kerlann.com/boutique-en-ligne/')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'LkaJlo.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1043-mini-gouter-rond-chocolat-168g-belle-france-3258561020815.html')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'ALlpIK.jpg', 'https://www.biscuiterie-de-kerlann.com/boutique-en-ligne/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'dbmoGK.jpg', 'https://world-nb.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'inJeKP.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1043-mini-gouter-rond-chocolat-168g-belle-france-3258561020815.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'fCCpLh.jpg', 'https://world-st.openfoodfacts.org/product/3258561020501/barquettes-fraise-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'bEeFDl.jpg', 'https://world-de.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'GLeEAd.webp', 'https://www.lepetitdepot.com/en/catalog/sweet-groceries/pocket-biscuits/belle-france-chocolate-barquette-120g')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'ppnkfO.jpg', 'https://www.bienmanger.com/1F33055_Boite_Assortiment_Biscuits_Fins_Maxim.html')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'LfDgpG.png', 'https://www.bienmanger.com/1F33055_Boite_Assortiment_Biscuits_Fins_Maxim.html')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'AHmKjI.png', 'https://www.lepetitdepot.com/en/catalog/sweet-groceries/pocket-biscuits/belle-france-chocolate-barquette-120g')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'eCbepM.jpg', 'https://world-de.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'mGiAnO.jpg', 'https://www.bienmanger.com/1F33055_Boite_Assortiment_Biscuits_Fins_Maxim.html')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'fbpmHk.jpg', 'https://theculturetrip.com/europe/france/articles/le-gouter-is-frances-answer-to-british-afternoon-tea/')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'LIHjIm.jpg', 'https://www.lepetitdepot.com/en/catalog/sweet-groceries/pocket-biscuits/belle-france-chocolate-barquette-120g')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'LgffBL.png', 'https://theculturetrip.com/europe/france/articles/le-gouter-is-frances-answer-to-british-afternoon-tea/')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'bbNAko.jpg', 'https://www.bienmanger.com/1F33055_Boite_Assortiment_Biscuits_Fins_Maxim.html')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'fcnplg.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1035-barres-gouter-pocket-x6-125g-belle-france-3258561020570.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'lnjOoL.jpg', 'https://world-st.openfoodfacts.org/product/3258561020501/barquettes-fraise-belle-france')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'Llejfl.png', 'https://www.bienmanger.com/1F33055_Boite_Assortiment_Biscuits_Fins_Maxim.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'HmIFKi.jpg', 'https://world-st.openfoodfacts.org/product/3258561020501/barquettes-fraise-belle-france')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'ldOFKB.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1035-barres-gouter-pocket-x6-125g-belle-france-3258561020570.html')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'chgGbg.jpg', 'https://world.openfoodfacts.org/product/3258561021379/assortiment-de-biscuits-fins-belle-france')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'lmdGGL.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1035-barres-gouter-pocket-x6-125g-belle-france-3258561020570.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'nIdkJm.jpg', 'https://world-st.openfoodfacts.org/product/3258561020501/barquettes-fraise-belle-france')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'kNHngE.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1035-barres-gouter-pocket-x6-125g-belle-france-3258561020570.html')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'enOjPG.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1035-barres-gouter-pocket-x6-125g-belle-france-3258561020570.html')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'NfgPgN.webp', 'https://www.marmiton.org/recettes/recette_barquettes-a-la-fraise_222081.aspx')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'kOebbN.png', 'https://www.marmiton.org/recettes/recette_barquettes-a-la-fraise_222081.aspx')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'AcJjOc.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/belle-france')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'AmaJId.webp', 'https://www.marmiton.org/recettes/recette_barquettes-a-la-fraise_222081.aspx')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'hCnpHg.jpg', 'https://world.openfoodfacts.org/product/3258561021379/assortiment-de-biscuits-fins-belle-france')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'FGjeIA.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/belle-france')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'MCHeAL.png', 'https://www.marmiton.org/recettes/recette_barquettes-a-la-fraise_222081.aspx')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'IkPpGF.webp', 'https://www.marmiton.org/recettes/recette_barquettes-a-la-fraise_222081.aspx')
insert into image (query, filename, site) values ('Barres goûter pocket - Belle France', 'ABHLoN.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/belle-france')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'ieGlKe.jpg', '[?25lhttps://www.amazon.fr/Frey-Chocolat-Fourr%C3%A9es-Noisettes-Certifi%C3%A9/dp/B009ES1VKC')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'mghgao.jpg', 'https://world.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('Barquettes fraise - Belle France', 'LMmjNc.jpg', 'https://world-th.openfoodfacts.org/product/3258561020501/barquettes-fraise-belle-france')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'JPKoaL.gif', 'https://www.linguee.com/french-english/translation/chocolat+au+lait+fourr%C3%A9.html')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'MIkebP.jpg', 'https://world-de.openfoodfacts.org/produkt/3258561018300/biscuit-epeautre-et-sesame-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'BAjmkB.png', 'https://www.simpleetgourmand.fr/recettes/biscuits-sesame-epeautre/')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'LBiKak.jpg', 'https://world.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'mhpGEn.jpg', 'https://www.simpleetgourmand.fr/recettes/biscuits-sesame-epeautre/')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'LnNOkn.jpg', 'https://fr.openfoodfacts.org/produit/3258561022413/barre-chocolat-fourre-lait-belle-france')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'MBbpdc.jpg', 'https://world.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'eAbJnD.png', 'https://www.simpleetgourmand.fr/recettes/biscuits-sesame-epeautre/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'ohfpBa.jpg', 'https://www.simpleetgourmand.fr/recettes/biscuits-sesame-epeautre/')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'ANIpeb.jpg', 'https://fr.openfoodfacts.org/produit/3258561022413/barre-chocolat-fourre-lait-belle-france')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'EnDiKl.jpg', 'https://world.openfoodfacts.org/product/3258561021379/assortiment-de-biscuits-fins-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'gnFAod.jpg', 'https://www.simpleetgourmand.fr/recettes/biscuits-sesame-epeautre/')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'oFoPAN.jpg', 'https://world.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'cNEnAO.png', 'https://www.fauchon.com/en/33-fauchon-fine-biscuits-assortment-1018345/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'HkAKPE.jpg', 'https://www.ptitchef.com/recettes/biscuit-au-sesame')
insert into image (query, filename, site) values ('Assortiment de Biscuits Fins - Belle France', 'elnCkg.jpg', 'https://www.fauchon.com/en/33-fauchon-fine-biscuits-assortment-1018345/')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'kMflbN.jpg', 'https://fr.openfoodfacts.org/produit/3258561022413/barre-chocolat-fourre-lait-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'IoNDGn.jpg', 'https://www.ptitchef.com/recettes/biscuit-au-sesame')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'chafgc.jpg', 'https://www.gettyimages.fr/illustrations/barre-chocolat')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'KAhDcC.png', 'https://www.eatlivetravelwrite.com/2022/04/barquettes-au-chocolat-recipe-recette/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'ObKMlh.jpg', 'https://www.ptitchef.com/recettes/biscuit-au-sesame')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'PndEKJ.jpg', 'https://www.gettyimages.fr/illustrations/barre-chocolat')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'HPFgMh.png', 'https://www.eatlivetravelwrite.com/2022/04/barquettes-au-chocolat-recipe-recette/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'OnbFKm.jpg', 'https://www.ptitchef.com/recettes/biscuit-au-sesame')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'Kmfldd.jpg', 'https://www.eatlivetravelwrite.com/2022/04/barquettes-au-chocolat-recipe-recette/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'pGfGED.jpg', 'https://www.ptitchef.com/recettes/biscuit-au-sesame')
insert into image (query, filename, site) values ('Barquettes Chocolat - Belle France', 'lhdGCc.jpg', 'https://www.facebook.com/easyshopehden/posts/1466620830208800/')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'PGENcE.jpg', 'https://www.cuisineactuelle.fr/recettes/petits-biscuits-d-epeautre-283200')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'HCEdad.jpg', 'https://world-ar.openfoodfacts.org/mountaj/3258561021164/barre-chocolat-lait-fourr%C3%A9-au-lait-belle-france')
insert into image (query, filename, site) values ('Biscuit epeautre et sesame - Belle France', 'GNBoFM.jpg', 'https://www.cuisineactuelle.fr/recettes/petits-biscuits-d-epeautre-283200')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'bnEdPg.jpg', 'https://world-ar.openfoodfacts.org/mountaj/3258561021164/barre-chocolat-lait-fourr%C3%A9-au-lait-belle-france')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'FkMCpe.jpg', '[?25lhttps://www.gettyimages.com/photos/biscuit')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'gbLNhg.jpg', 'https://www.gettyimages.com/photos/biscuit')
insert into image (query, filename, site) values ('Cookies - Belle France', 'oneFBc.jpg', '[?25lhttps://www.gettyimages.com/photos/cookie')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'ibkbhl.jpg', 'https://www.gettyimages.com/photos/biscuit')
insert into image (query, filename, site) values ('Cookies - Belle France', 'DknpJe.jpg', 'https://www.gettyimages.com/photos/cookie')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'aAOcgN.jpg', 'https://www.gettyimages.com/photos/biscuit')
insert into image (query, filename, site) values ('Cookies - Belle France', 'haPhAn.jpg', 'https://www.gettyimages.com/photos/cookie')
insert into image (query, filename, site) values ('Cookies - Belle France', 'PGdjlp.jpg', 'https://www.gettyimages.com/photos/cookie')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'hNLlcn.jpg', 'https://www.gettyimages.com/photos/biscuit')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'kBdjjD.jpg', 'https://www.houra.fr/cora-biscuits-cuillers-degustation-125g/1255187/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'hgcbPc.jpg', 'https://www.houra.fr/cora-biscuits-cuillers-degustation-125g/1255187/')
insert into image (query, filename, site) values ('Cookies - Belle France', 'ldFeJm.jpg', 'https://www.gettyimages.com/photos/cookie')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'KEnAnG.jpg', 'https://fr.openfoodfacts.org/categorie/fr:biscuits/marque/belle-france')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'HMcGIf.jpg', 'https://www.gettyimages.com/photos/savoury-biscuits')
insert into image (query, filename, site) values ('Cookies - Belle France', 'BFmLkC.jpg', 'https://expertphotography.com/creative-cookie-photography/')
insert into image (query, filename, site) values ('Cookies - Belle France', 'hcnLLe.jpg', 'https://expertphotography.com/creative-cookie-photography/')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'FAclfa.jpg', 'https://www.gettyimages.com/photos/savoury-biscuits')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'gjmEEo.jpg', 'https://fr.openfoodfacts.org/categorie/fr:biscuits/marque/belle-france')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'gGPJIG.png', '[?25lhttps://www.openculture.com/2021/07/a-gallery-of-1800-super-high-resolution-images-of-classic-paintings.html')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'Cddomc.jpg', 'https://www.gettyimages.com/photos/savoury-biscuits')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'hjHhkA.png', '[?25lhttps://www.chocolat-weiss.fr/fr/50-du-chocolat-au-lait-a-croquer-en-tablette-ou-a-patisser')
insert into image (query, filename, site) values ('Cookies - Belle France', 'JDFfHN.jpg', 'https://expertphotography.com/creative-cookie-photography/')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'gpGDPl.jpg', 'https://www.chocolat-weiss.fr/fr/50-du-chocolat-au-lait-a-croquer-en-tablette-ou-a-patisser')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'EfAaoG.jpg', 'https://www.gettyimages.com/photos/savoury-biscuits')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'meAinD.jpg', 'https://fr.openfoodfacts.org/categorie/fr:biscuits/marque/belle-france')
insert into image (query, filename, site) values ('Cookies - Belle France', 'beLKdJ.png', 'https://expertphotography.com/creative-cookie-photography/')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'BCclPo.jpg', 'https://www.chocolat-weiss.fr/fr/50-du-chocolat-au-lait-a-croquer-en-tablette-ou-a-patisser')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'NnPdfk.jpg', 'https://www.gettyimages.com/photos/savoury-biscuits')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'eGOeea.jpg', 'https://www.chocolat-weiss.fr/fr/50-du-chocolat-au-lait-a-croquer-en-tablette-ou-a-patisser')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'kdfeDI.jpg', 'https://fr.openfoodfacts.org/categorie/fr:biscuits/marque/belle-france')
insert into image (query, filename, site) values ('Belle France', 'bIdGEp.jpg', '[?25lhttps://www.gettyimages.co.uk/photos/paris-belle-epoque')
insert into image (query, filename, site) values ('Cookies - Belle France', 'FGjcEh.jpg', 'https://expertphotography.com/creative-cookie-photography/')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'BAcGFF.jpg', 'https://www.chocolat-weiss.fr/fr/50-du-chocolat-au-lait-a-croquer-en-tablette-ou-a-patisser')
insert into image (query, filename, site) values ('Belle France', 'lIHjai.jpg', 'https://www.dreamstime.com/photos-images/belle-france-ile.html')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'glNDiG.jpg', 'https://fr.openfoodfacts.org/categorie/fr:biscuits/marque/belle-france')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'moBgha.jpg', 'https://world.openfoodfacts.org/product/3258561020969/biscuits-petit-beurre-chocolat-noisette-150-g-lot-de-6-belle-france')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'JbaIpj.webp', '[?25lhttps://www.marmiton.org/recettes/recette_cookies-aux-noisettes-et-aux-amandes_52196.aspx')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'cNmFAh.jpg', 'https://www.amazon.fr/Neslt%C3%A9-Chocolat-lait-tablette-170g/dp/B07DJ91N94')
insert into image (query, filename, site) values ('Belle France', 'hEPbID.jpg', 'https://www.dreamstime.com/photos-images/belle-france-ile.html')
insert into image (query, filename, site) values ('Cookies - Belle France', 'kFnJlD.jpg', 'https://www.tasteofhome.com/collection/french-cookies/')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'Mifocl.webp', 'https://www.marmiton.org/recettes/recette_cookies-aux-noisettes-et-aux-amandes_52196.aspx')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'lNNMnD.jpg', 'https://www.amazon.fr/Neslt%C3%A9-Chocolat-lait-tablette-170g/dp/B07DJ91N94')
insert into image (query, filename, site) values ('Cookies - Belle France', 'liEOLf.png', 'https://www.tasteofhome.com/collection/french-cookies/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'bIjIel.png', 'https://www.auchan.fr/auchan-biscuits-cuillers-degustation-aux-oeufs-frais-sachets-fraicheur/pr-C1245421')
insert into image (query, filename, site) values ('Belle France', 'IADFIf.jpg', 'https://www.dreamstime.com/photos-images/belle-france-ile.html')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'jjDmoI.webp', 'https://www.marmiton.org/recettes/recette_cookies-aux-noisettes-et-aux-amandes_52196.aspx')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'biFifk.jpg', 'https://www.amazon.fr/Neslt%C3%A9-Chocolat-lait-tablette-170g/dp/B07DJ91N94')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'PBGnMh.png', 'https://www.auchan.fr/auchan-biscuits-cuillers-degustation-aux-oeufs-frais-sachets-fraicheur/pr-C1245421')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'HbeaIa.jpg', 'https://www.marmiton.org/recettes/recette_cookies-aux-noisettes-et-aux-amandes_52196.aspx')
insert into image (query, filename, site) values ('Cookies - Belle France', 'COddCL.jpg', 'https://www.tasteofhome.com/collection/french-cookies/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'iMjCCG.png', 'https://www.auchan.fr/auchan-biscuits-cuillers-degustation-aux-oeufs-frais-sachets-fraicheur/pr-C1245421')
insert into image (query, filename, site) values ('Belle France', 'lmCedp.jpg', 'https://www.dreamstime.com/photos-images/belle-france-ile.html')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'DLIDbN.jpg', 'https://www.amazon.fr/Neslt%C3%A9-Chocolat-lait-tablette-170g/dp/B07DJ91N94')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'HofFFN.jpg', 'https://thegoodlifefrance.com/classic-french-beurre-noisette/')
insert into image (query, filename, site) values ('Belle France', 'EodbCa.jpg', 'https://www.dreamstime.com/photos-images/belle-france-ile.html')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'jggDMg.jpg', 'https://www.amazon.fr/Neslt%C3%A9-Chocolat-lait-tablette-170g/dp/B07DJ91N94')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'miocbK.jpg', 'https://thegoodlifefrance.com/classic-french-beurre-noisette/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'odiNHo.png', 'https://www.auchan.fr/auchan-biscuits-cuillers-degustation-aux-oeufs-frais-sachets-fraicheur/pr-C1245421')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'GdiKHF.jpg', 'https://world.openfoodfacts.org/product/3258561020969/biscuits-petit-beurre-chocolat-noisette-150-g-lot-de-6-belle-france')
insert into image (query, filename, site) values ('Cookies - Belle France', 'ceOGCH.jpg', 'https://thekitchencommunity.org/french-cookies/')
insert into image (query, filename, site) values ('Belle France', 'HcGccl.webp', 'https://www.123rf.com/stock-photo/belle.html')
insert into image (query, filename, site) values ('Cookies - Belle France', 'JKhpGi.jpg', 'https://thekitchencommunity.org/french-cookies/')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'KfLODg.jpg', 'https://thegoodlifefrance.com/classic-french-beurre-noisette/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'NOfJPa.png', 'https://www.auchan.fr/auchan-biscuits-cuillers-degustation-aux-oeufs-frais-sachets-fraicheur/pr-C1245421')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'POlDlc.jpg', 'https://thegoodlifefrance.com/classic-french-beurre-noisette/')
insert into image (query, filename, site) values ('Belle France', 'mmnBpP.webp', 'https://www.123rf.com/stock-photo/belle.html')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'lFJmPp.jpg', 'https://world-ar.openfoodfacts.org/mountaj/3258561021164/barre-chocolat-lait-fourr%C3%A9-au-lait-belle-france')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'DnHGBc.webp', 'https://www.france-hotel-guide.com/en/blog/french-biscuits/')
insert into image (query, filename, site) values ('Belle France', 'FBadAb.webp', 'https://www.123rf.com/stock-photo/belle.html')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'DOpFkl.jpg', 'https://thegoodlifefrance.com/classic-french-beurre-noisette/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'gddNHH.jpg', 'https://world-de.openfoodfacts.org/produkt/3258561019116/biscuits-cuillers-d%C3%A9gustation-aux-oeufs-frais-belle-fran%C3%A7e')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'ODnafG.webp', 'https://www.france-hotel-guide.com/en/blog/french-biscuits/')
insert into image (query, filename, site) values ('Cookies - Belle France', 'JGPhiH.jpg', 'https://thekitchencommunity.org/french-cookies/')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'DNkCEg.jpg', 'https://world-ar.openfoodfacts.org/mountaj/3258561021164/barre-chocolat-lait-fourr%C3%A9-au-lait-belle-france')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'aiegnO.webp', 'https://www.france-hotel-guide.com/en/blog/french-biscuits/')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'mkLabL.webp', 'https://www.france-hotel-guide.com/en/blog/french-biscuits/')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'IfaDjC.jpg', 'https://world-de.openfoodfacts.org/produkt/3258561019116/biscuits-cuillers-d%C3%A9gustation-aux-oeufs-frais-belle-fran%C3%A7e')
insert into image (query, filename, site) values ('Belle France', 'moCOGG.webp', 'https://www.123rf.com/stock-photo/belle.html')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'LhNmIp.webp', 'https://www.france-hotel-guide.com/en/blog/french-biscuits/')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'iAKdEd.jpg', 'https://world-ar.openfoodfacts.org/mountaj/3258561021164/barre-chocolat-lait-fourr%C3%A9-au-lait-belle-france')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'GBcgkK.jpg', 'https://www.marmiton.org/recettes/recette_cookies-a-la-noisette_21586.aspx')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'mObBfF.jpg', 'https://www.byacb4you.com/pitch-maison-pain-lait-chocolat.html')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'FJONeF.jpg', 'https://world-de.openfoodfacts.org/produkt/3258561019116/biscuits-cuillers-d%C3%A9gustation-aux-oeufs-frais-belle-fran%C3%A7e')
insert into image (query, filename, site) values ('Biscuits fins - Belle France', 'bekMfD.gif', 'https://www.linguee.com/french-english/translation/biscuits+fins.html')
insert into image (query, filename, site) values ('Belle France', 'kDHBpb.webp', 'https://www.123rf.com/stock-photo/belle.html')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'CnmbJo.webp', 'https://www.marmiton.org/recettes/recette_cookies-a-la-noisette_21586.aspx')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'KaBAJb.webp', 'https://www.marmiton.org/recettes/recette_cookies-a-la-noisette_21586.aspx')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'AnGegf.svg', 'https://www.auchan.fr/auchan-biscuits-cuillers-special-dessert-aux-oeufs-frais-sachets-fraicheur/pr-C1243593')
insert into image (query, filename, site) values ('Belle France', 'alOdEb.jpg', 'https://www.freeimages.com/search/belle')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'fPmfio.webp', 'https://www.marmiton.org/recettes/recette_cookies-a-la-noisette_21586.aspx')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'fMilHK.jpg', 'https://www.byacb4you.com/pitch-maison-pain-lait-chocolat.html')
insert into image (query, filename, site) values ('Biscuits cuillers dégustation aux oeufs frais - Belle Françe', 'CmiMip.png', 'https://www.myfitnesspal.com/fr/food/calories/biscuits-cuillers-aux-oeufs-frais-228006140')
insert into image (query, filename, site) values ('Belle France', 'gEahaH.jpg', 'https://www.freeimages.com/search/belle')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'HIEfEL.jpg', 'https://www.byacb4you.com/pitch-maison-pain-lait-chocolat.html')
insert into image (query, filename, site) values ('Belle France', 'LJGGpf.png', 'https://www.freeimages.com/search/belle')
insert into image (query, filename, site) values ('Belle France', 'ONdfnI.png', 'https://www.freeimages.com/search/belle')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'dPLlPk.jpg', 'https://world-eu.openfoodfacts.org/product/3258561021096/cookies-noisette-belle-france')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'moOgIJ.jpg', 'https://world-nl.openfoodfacts.org/product/3258561018072/boscuits-tablette-au-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'KGLakC.jpg', 'https://world-eu.openfoodfacts.org/product/3258561021096/cookies-noisette-belle-france')
insert into image (query, filename, site) values ('Barre chocolat lait, fourré au lait - Belle France', 'ifEGeH.png', 'https://www.myfitnesspal.com/food/calories/barre-chocolatee-fourree-au-lait-139534819')
insert into image (query, filename, site) values ('Cookies Noisettes - Belle France', 'LMBkCE.jpg', 'https://world-eu.openfoodfacts.org/product/3258561021096/cookies-noisette-belle-france')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'JCpDnH.jpg', 'https://world-nl.openfoodfacts.org/product/3258561018072/boscuits-tablette-au-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'pJBLjK.jpg', 'https://world-nl.openfoodfacts.org/product/3258561018072/boscuits-tablette-au-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'hEpCoG.jpg', 'https://world-nl.openfoodfacts.org/product/3258561018072/boscuits-tablette-au-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'nPlbCn.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'CAjcFN.jpg', '[?25lhttps://biscuitsetcompagnie.com/85-tuiles-amandes.html')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'faAPla.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'Idcpol.jpg', 'https://biscuitsetcompagnie.com/85-tuiles-amandes.html')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'hGcmKo.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'kNoNii.png', 'https://biscuitsetcompagnie.com/85-tuiles-amandes.html')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'BKNLna.jpg', 'https://biscuitsetcompagnie.com/85-tuiles-amandes.html')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'HNeHoJ.jpg', 'https://biscuitsetcompagnie.com/85-tuiles-amandes.html')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'FFaINI.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'mpJAAF.jpg', 'https://www.elle.fr/Elle-a-Table/Recettes-de-cuisine/Tuiles-aux-amandes-2665059')
insert into image (query, filename, site) values ('Boscuits tablette au chocolat au lait - Belle France', 'eekdhj.jpg', 'https://world.openfoodfacts.org/brand/belle-france/brand/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'PAkOPI.jpg', 'https://www.elle.fr/Elle-a-Table/Recettes-de-cuisine/Tuiles-aux-amandes-2665059')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'DDGKAg.jpg', 'https://www.elle.fr/Elle-a-Table/Recettes-de-cuisine/Tuiles-aux-amandes-2665059')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'bpkMDJ.jpg', 'https://www.elle.fr/Elle-a-Table/Recettes-de-cuisine/Tuiles-aux-amandes-2665059')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'bACMMg.jpg', 'https://www.elle.fr/Elle-a-Table/Recettes-de-cuisine/Tuiles-aux-amandes-2665059')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'hgpgPK.jpg', 'https://shop.cabf.eu/produit/tuiles-amandes-100g-bf/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'jhgFpe.png', 'https://shop.cabf.eu/produit/tuiles-amandes-100g-bf/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'hAgCIb.jpg', 'https://shop.cabf.eu/produit/tuiles-amandes-100g-bf/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'mgeLng.jpg', 'https://shop.cabf.eu/produit/tuiles-amandes-100g-bf/')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'PFMnNE.jpg', 'https://www.istockphoto.com/fr/photos/tuiles-aux-amandes')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'mgnEOK.png', '[?25lhttps://cuisine.journaldesfemmes.fr/recette-galette-bretonne')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'Calllk.jpg', 'https://www.istockphoto.com/fr/photos/tuiles-aux-amandes')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'PMgijp.png', 'https://www.openculture.com/2021/07/a-gallery-of-1800-super-high-resolution-images-of-classic-paintings.html')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'ALgkLd.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-tuiles-amandes-100g')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'iDCIIE.jpg', '[?25lhttps://fr.freepik.com/photos/gaufrette')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'ncflHI.jpg', 'https://world-gl.openfoodfacts.org/produto/3258563020226/galettes-bretonnes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'MBJGpJ.webp', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-tuiles-amandes-100g')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'PLlfjg.png', 'https://fr.freepik.com/photos/gaufrette')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'hENkiB.png', 'https://fr.freepik.com/photos/gaufrette')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'cLheII.jpg', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-tuiles-amandes-100g')
insert into image (query, filename, site) values ('Etui Tuiles Aux Amandes 100G Belle France', 'LiPOBj.webp', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-tuiles-amandes-100g')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'CnjpEL.jpg', 'https://fr.freepik.com/photos/gaufrette')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'BOdlmc.png', 'https://fr.freepik.com/photos/gaufrette')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'NmcCic.jpg', 'https://www.thespruceeats.com/gaufrettes-recipe-1374959')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'DnjgAe.jpg', 'https://www.thespruceeats.com/gaufrettes-recipe-1374959')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'kHopEJ.webp', '[?25lhttps://www.marmiton.org/recettes/recette_galettes-sablees_90001.aspx')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'mncpbE.jpg', 'https://www.thespruceeats.com/gaufrettes-recipe-1374959')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'kJIlhO.jpg', 'https://www.thespruceeats.com/gaufrettes-recipe-1374959')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'NaFeBD.jpg', 'https://www.thespruceeats.com/gaufrettes-recipe-1374959')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'mnNgkG.webp', 'https://www.marmiton.org/recettes/recette_galettes-sablees_90001.aspx')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'hemPgb.jpg', 'https://www.cuisineactuelle.fr/recettes/gaufrette-vanille-321830')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'GCIlfN.webp', 'https://www.marmiton.org/recettes/recette_galettes-sablees_90001.aspx')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'OjGnPn.jpg', 'https://www.cuisineactuelle.fr/recettes/gaufrette-vanille-321830')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'BpkiCM.webp', 'https://www.marmiton.org/recettes/recette_galettes-sablees_90001.aspx')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'GMajmN.jpg', 'https://www.cuisineactuelle.fr/recettes/gaufrette-vanille-321830')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'AiHOcE.jpg', 'https://www.cuisineactuelle.fr/recettes/gaufrette-vanille-321830')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'dfMiGf.jpg', 'https://world-gl.openfoodfacts.org/produto/3258563020226/galettes-bretonnes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'dFgJba.png', 'https://www.labellevie.com/produit/34036/gaufrettes-a-la-vanille-bourbon-de-madagascar-albert-menes-85-g')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'neCPGo.jpg', 'https://world-gl.openfoodfacts.org/produto/3258563020226/galettes-bretonnes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'BOkMFO.png', 'https://www.openculture.com/2021/07/a-gallery-of-1800-super-high-resolution-images-of-classic-paintings.html')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'dhEOIG.jpg', 'https://world-sl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'ldjFfp.jpg', 'https://www.labellevie.com/produit/34036/gaufrettes-a-la-vanille-bourbon-de-madagascar-albert-menes-85-g')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'NJmLKp.png', 'https://cuisine.journaldesfemmes.fr/recette/348786-galettes-bretonnes')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'giFeJn.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/gaufrette-vanille-175g-belle-france-ftm00228/')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'DAmnNl.jpg', 'https://cuisine.journaldesfemmes.fr/recette/348786-galettes-bretonnes')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'fOAolg.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/gaufrette-vanille-175g-belle-france-ftm00228/')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'pmbNOf.jpg', '[?25lhttps://www.freepik.com/photos/french-galette/5')
insert into image (query, filename, site) values ('Gaufrette A La Vanille 175gr - Belle France', 'cFigHF.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/gaufrette-vanille-175g-belle-france-ftm00228/')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'jknOAm.jpg', 'https://www.freepik.com/photos/french-galette/5')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'cMpJHp.jpg', 'https://hellonelo.com/recettes/recette-galette-bretonne/')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'GbLkAG.jpg', 'https://www.freepik.com/photos/french-galette/5')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'cePNLO.png', 'https://www.freepik.com/photos/french-galette/5')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'ANLHdM.jpg', '[?25lhttps://world-ca.openfoodfacts.org/product/3258561019352/gouters-parfum-vanille-belle-france')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'kPKfCn.jpg', 'https://www.freepik.com/photos/french-galette/5')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'NihjHC.jpg', '[?25lhttps://world-qu.openfoodfacts.org/product/3258561019406/go%C3%BBters-fourr%C3%A9s-parfum-vanille-belle-france')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'HoADgN.jpg', 'https://hellonelo.com/recettes/recette-galette-bretonne/')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'pgMECf.jpg', 'https://www.gettyimages.ca/photos/galettas-des-rois')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'JNfJkM.jpg', 'https://world-qu.openfoodfacts.org/product/3258561019406/go%C3%BBters-fourr%C3%A9s-parfum-vanille-belle-france')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'LcdfCB.jpg', 'https://world.openfoodfacts.org/product/3258561020877/gouters-parfum-fraise-belle-france')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'FjFfbp.jpg', 'https://hellonelo.com/recettes/recette-galette-bretonne/')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'OHEOfd.jpg', 'https://world.openfoodfacts.org/product/3258561020877/gouters-parfum-fraise-belle-france')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'HgbNBg.jpg', 'https://www.mesinspirationsculinaires.com/article-galette-bretonne-complete.html')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'miiPnG.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-vanille-92986449')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'LFGAGH.jpg', 'https://www.gettyimages.com/photos/gallette')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'pMaaPp.jpg', 'https://www.mesinspirationsculinaires.com/article-galette-bretonne-complete.html')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'GDnEko.jpg', 'https://www.gettyimages.com/photos/gallette')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'oHdoFm.jpg', 'https://www.mesinspirationsculinaires.com/article-galette-bretonne-complete.html')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'KCaJOl.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-vanille-92986449')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'EdgIGi.jpg', 'https://www.gettyimages.com/photos/gallette')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'IJfecK.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-vanille-92986449')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'gHNoGF.jpg', 'https://www.gettyimages.com/photos/gallette')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'GMfMkl.jpg', 'https://www.mesinspirationsculinaires.com/article-galette-bretonne-complete.html')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'jnFEFO.jpg', 'https://world-sl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'NBBdJe.jpg', 'https://www.gettyimages.com/photos/gallette')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'mGceEJ.jpg', 'https://www.gettyimages.com/photos/galettas-des-rois')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'jOefAK.jpg', 'https://www.gettyimages.com/photos/galettas-des-rois')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'BeEOiF.jpg', 'https://www.mesinspirationsculinaires.com/article-galette-bretonne-complete.html')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'NbfkAc.jpg', 'https://world-sl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'pooBAJ.jpg', 'https://www.gettyimages.com/photos/galettas-des-rois')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'fGkGFK.jpg', 'https://world-sl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'gNgfpo.jpg', 'https://world-fr.openfoodfacts.org/produit/3258563020226/galettes-bretonnes-les-delices-de-belle-france')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'lJOnNp.jpg', 'https://world-sl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'HnPFpC.jpg', 'https://www.gettyimages.com/photos/galettas-des-rois')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'cJECak.png', 'https://www.promocatalogues.fr/magasins/coccimarket/offres/galettes-sablees-pur-beurre-les-delices-de-belle-france-offre-20656200/')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'hngdBE.jpg', 'https://www.gettyimages.com/photos/galettas-des-rois')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'EdJbKB.jpg', 'https://saltandspine.substack.com/p/swedish-chocolate-oatmeal-cookies')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'MMILil.jpg', 'https://world.openfoodfacts.org/product/3258561020877/gouters-parfum-fraise-belle-france')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'bCFDlE.jpg', 'https://saltandspine.substack.com/p/swedish-chocolate-oatmeal-cookies')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'GgOgbL.png', 'https://www.promocatalogues.fr/magasins/coccimarket/offres/galettes-sablees-pur-beurre-les-delices-de-belle-france-offre-20656200/')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'GncEfB.jpg', 'https://world-ms.openfoodfacts.org/produk/3258561020907/go%C3%BBters-fourr%C3%A9s-parfum-chocolat-belle-france')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'BjCJoa.jpg', 'https://world-fr.openfoodfacts.org/produit/3258563020226/galettes-bretonnes-les-delices-de-belle-france')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'dpLllG.png', 'https://www.promocatalogues.fr/magasins/coccimarket/offres/galettes-sablees-pur-beurre-les-delices-de-belle-france-offre-20656200/')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'gOECnK.jpg', 'https://delices-de-bretagne.fr/')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'FgmlHB.png', 'https://www.promocatalogues.fr/magasins/coccimarket/offres/galettes-sablees-pur-beurre-les-delices-de-belle-france-offre-20656200/')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'opGfhm.jpg', 'https://saltandspine.substack.com/p/swedish-chocolate-oatmeal-cookies')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'CBFhcE.png', 'https://www.promocatalogues.fr/magasins/coccimarket/offres/galettes-sablees-pur-beurre-les-delices-de-belle-france-offre-20656200/')
insert into image (query, filename, site) values ('Galettes bretonnes - Les Délices de Belle France', 'HEelmp.jpg', 'https://delices-de-bretagne.fr/')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'CoFNmj.jpg', 'https://world-ms.openfoodfacts.org/produk/3258561020907/go%C3%BBters-fourr%C3%A9s-parfum-chocolat-belle-france')
insert into image (query, filename, site) values ('Galettes Suédoises - Belle France', 'PCKJbP.jpg', 'https://www.pinterest.com/pin/528398968777509867/')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'OjleBK.jpg', 'https://world.openfoodfacts.org/product/3258561020877/gouters-parfum-fraise-belle-france')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'clfLap.jpg', 'https://world.openfoodfacts.org/product/3258561020877/gouters-parfum-fraise-belle-france')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'Apnhii.jpg', 'https://world-ms.openfoodfacts.org/produk/3258561020907/go%C3%BBters-fourr%C3%A9s-parfum-chocolat-belle-france')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'AgCEbg.jpg', 'https://incibeauty.com/en/produit/3258561640228')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'gjFOjJ.jpg', 'https://world-ms.openfoodfacts.org/produk/3258561020907/go%C3%BBters-fourr%C3%A9s-parfum-chocolat-belle-france')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'eiEMcC.jpg', 'https://world-mi.openfoodfacts.org/product/3258563020295/galettes-sabl%C3%A9es-aux-fruits-rouges-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'GOLcNM.jpg', 'https://world.openfoodfacts.org/product/3257980495938/gouters-fourres-parfum-vanille')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'lMIodf.jpg', 'https://world-nl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'eNgNkb.jpg', 'https://incibeauty.com/en/produit/3258561640228')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'nPPdde.jpg', 'https://incibeauty.com/en/produit/3258561640228')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'McdphN.jpg', 'https://incibeauty.com/en/produit/3258561640228')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'OhEbmf.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-fraise-139576352')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'ioncLO.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-fraise-139576352')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'FGngmG.jpg', 'https://world.openfoodfacts.org/product/3257980495938/gouters-fourres-parfum-vanille')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'ganPbC.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-fraise-139576352')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'oEKjic.jpg', 'https://world.openfoodfacts.org/product/3257980495938/gouters-fourres-parfum-vanille')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'lLiMmJ.gif', 'https://www.linguee.com/french-english/translation/parfum+de+fraise.html')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'dLDpjd.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-chocolat-carre-1507296795')
insert into image (query, filename, site) values ('Goûters parfum fraise - Belle France', 'HjcPbh.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-fraise-139521763')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'LIchIE.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-chocolat-carre-1507296795')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'OIpcdG.png', '[?25lhttps://market.lamater.net/products/langues-de-chat-belle-france')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'NpAJBN.jpg', 'https://world-nl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Goûters fourrés parfum vanille - Belle France', 'fLNLkG.png', 'https://www.myfitnesspal.com/food/calories/gouters-fourres-parfum-chocolat-carre-1507296795')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'plfFca.jpg', 'https://cadismarket.com/fr/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'knJcNN.jpg', 'https://world-nl.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'DbGoHb.jpg', 'https://cadismarket.com/fr/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'OjNMGD.jpg', 'https://cadismarket.com/fr/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'pnNPmM.jpg', '[?25lhttps://www.pardonyourfrench.com/raspberry-jam-filled-sable-sandwiches-lunettes-de-romans/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'IcELna.jpg', 'https://www.pardonyourfrench.com/raspberry-jam-filled-sable-sandwiches-lunettes-de-romans/')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'eIfABj.jpg', 'https://cadismarket.com/fr/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'CpFGhk.jpg', 'https://cadismarket.com/fr/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'NFobaO.jpg', 'https://www.pardonyourfrench.com/raspberry-jam-filled-sable-sandwiches-lunettes-de-romans/')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'NlpHGn.jpg', '[?25lhttps://www.instructables.com/Classic-French-Palmiers/')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'dKhaAm.jpg', 'https://www.instructables.com/Classic-French-Palmiers/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'pmfIMA.jpg', 'https://www.pardonyourfrench.com/raspberry-jam-filled-sable-sandwiches-lunettes-de-romans/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'Ghhffl.jpg', 'https://www.pardonyourfrench.com/raspberry-jam-filled-sable-sandwiches-lunettes-de-romans/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'iGjmAF.jpg', 'https://www.labellelunettefrancaise.com/la-belle-lunette-francaise')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'kggoMI.jpg', 'https://www.instructables.com/Classic-French-Palmiers/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'PhghFA.jpg', 'https://www.labellelunettefrancaise.com/la-belle-lunette-francaise')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'ncNAiF.jpg', 'https://www.instructables.com/Classic-French-Palmiers/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'cFMecC.jpg', 'https://www.labellelunettefrancaise.com/la-belle-lunette-francaise')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'aLcIPC.jpg', 'https://www.historyhit.com/guides/the-very-best-roman-sites-in-france/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'joEEfm.jpg', 'https://www.historyhit.com/guides/the-very-best-roman-sites-in-france/')
insert into image (query, filename, site) values ('Galettes Sablées aux Pommes - Les Délices de Belle France', 'iJhHDN.jpg', 'https://world-eu.openfoodfacts.org/product/3258563020271/galettes-sabl%C3%A9es-aux-pommes-les-d%C3%A9lices-de-belle-france')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'eekcJL.jpg', 'https://www.historyhit.com/guides/the-very-best-roman-sites-in-france/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'PFMPbo.jpg', 'https://www.istockphoto.com/photos/roman-empire')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'AiiCCP.jpg', 'https://www.istockphoto.com/photos/roman-empire')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'OAcbIb.png', 'https://www.openculture.com/2021/07/a-gallery-of-1800-super-high-resolution-images-of-classic-paintings.html')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'nGJnbb.jpg', 'https://www.istockphoto.com/photos/roman-empire')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'eopCLk.png', 'https://www.assortedeats.com/langue-de-chat/')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'iNKDAM.jpg', 'https://www.istockphoto.com/photos/roman-empire')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'mNEjfI.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'CbaeEO.gif', 'https://www.instructables.com/Classic-French-Palmiers/')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'EcoaMa.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'LpOAbl.jpg', 'https://www.istockphoto.com/photos/roman-empire')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'IIoGOi.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'Ljmkfo.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'eibLef.jpg', 'https://www.dreamstime.com/photos-images/palmiers.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'IcdGJn.jpg', 'https://cadismarket.com/en/biscuits-gateaux/1025-langues-de-chat-2x100g-belle-france-3258561020372.html')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'OCGKEK.jpg', 'https://my-french-grocery.com/product/strawberry-lunettes-de-romans-reflets-de-france/')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'GinJdO.jpg', 'https://www.dreamstime.com/photos-images/palmiers.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'fOCKFg.jpg', 'https://www.gettyimages.fr/photos/langue-de-belle-mere')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'GAHnkh.gif', 'https://my-french-grocery.com/product/strawberry-lunettes-de-romans-reflets-de-france/')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'NIJmAG.jpg', 'https://www.gettyimages.fr/photos/langue-de-belle-mere')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'MlOnln.png', 'https://my-french-grocery.com/product/strawberry-lunettes-de-romans-reflets-de-france/')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'EJDcpl.jpg', 'https://www.dreamstime.com/photos-images/palmiers.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'HiKaAF.jpg', 'https://www.gettyimages.fr/photos/langue-de-belle-mere')
insert into image (query, filename, site) values ('Lunettes de roman - Belle France', 'FlaIgf.png', 'https://my-french-grocery.com/product/strawberry-lunettes-de-romans-reflets-de-france/')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'jFhpab.jpg', '[?25lhttps://world-oc.openfoodfacts.org/produit/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'FElLAk.jpg', 'https://www.dreamstime.com/photos-images/palmiers.html')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'Pmojki.jpg', 'https://world-oc.openfoodfacts.org/produit/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'ngCGoB.jpg', 'https://www.gettyimages.fr/photos/langue-de-belle-mere')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'phIIPp.jpg', 'https://www.dreamstime.com/photos-images/palmiers.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'HfdpFk.jpg', 'https://www.gettyimages.fr/photos/langue-de-belle-mere')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'fCljcM.png', 'https://www.myfitnesspal.com/food/calories/barquettes-chocolat-noisette-1266463694')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'imjmcC.webp', 'https://www.123rf.com/stock-photo/palmiers.html')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'JeCMgD.png', 'https://www.myfitnesspal.com/food/calories/barquettes-chocolat-noisette-1266463694')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'jcJPAb.webp', 'https://www.123rf.com/stock-photo/palmiers.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'BLlFMp.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/langues-de-chat-belle-france-biscuits-delicieux-200g-sf00181/')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'hjHOMo.webp', 'https://www.123rf.com/stock-photo/palmiers.html')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'jmdOLo.jpg', 'https://world.openfoodfacts.org/product/3256225044085/mat-lou-barquettes-chocolat-noisette')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'EiNkcC.webp', 'https://www.123rf.com/stock-photo/palmiers.html')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'gKnNei.png', 'https://www.sodishop.com/shop/supermarche/alimentaire/langues-de-chat-belle-france-biscuits-delicieux-200g-sf00181/')
insert into image (query, filename, site) values ('Langues de chat - Belle France', 'HNIBCo.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/langues-de-chat-belle-france-biscuits-delicieux-200g-sf00181/')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'DFDfLp.jpg', 'https://world.openfoodfacts.org/product/3256225044085/mat-lou-barquettes-chocolat-noisette')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'mNGPfe.webp', 'https://www.123rf.com/stock-photo/palmiers.html')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'cFneDJ.jpg', 'https://www.canstockphoto.com/images-photos/palmiers.html')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'mbaHCm.jpg', 'https://www.canstockphoto.com/images-photos/palmiers.html')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'IkHmBp.jpg', 'https://world.openfoodfacts.org/product/3256225044085/mat-lou-barquettes-chocolat-noisette')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'OEGaLf.jpg', 'https://www.canstockphoto.com/images-photos/palmiers.html')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'JKMNpj.jpg', 'https://www.canstockphoto.com/images-photos/palmiers.html')
insert into image (query, filename, site) values ('Palmiers - Belle France', 'cDcBal.jpg', 'https://www.canstockphoto.com/images-photos/palmiers.html')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'bHIIfi.png', '[?25lhttps://www.stmichel.fr/nos-produits/detail/sable-nappe-bio')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'HDNBPA.png', 'https://www.stmichel.fr/nos-produits/detail/sable-nappe-bio')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'pkFPDP.png', 'https://www.stmichel.fr/nos-produits/detail/sable-nappe-bio')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'FENkhJ.png', 'https://www.stmichel.fr/nos-produits/detail/sable-nappe-bio')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'EKJIEF.jpg', 'https://world.openfoodfacts.org/product/3256225044085/mat-lou-barquettes-chocolat-noisette')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'dcGjlp.png', 'https://www.stmichel.fr/nos-produits/detail/sable-nappe-bio')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'Pkmfpm.jpg', 'https://world.openfoodfacts.org/product/3256225044085/mat-lou-barquettes-chocolat-noisette')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'GOIJOj.png', 'https://www.myfitnesspal.com/food/calories/belle-france-sable-nappes-chocolat-au-lait-148431221')
insert into image (query, filename, site) values ('Sables nappes au chocolat au lait - le reflexe bio - Belle France', 'eAbmce.png', 'https://www.myfitnesspal.com/food/calories/belle-france-sable-nappes-chocolat-au-lait-148431221')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'JfbBbn.jpg', 'https://world-ca.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'oihBni.jpg', 'https://world-ca.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'HGHemL.jpg', 'https://world-ca.openfoodfacts.org/product/3258561020563/barquettes-chocolat-noisette-belle-france')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'mkPLnA.png', 'https://www.myfitnesspal.com/food/calories/barquettes-chocolat-noisette-286616084')
insert into image (query, filename, site) values ('s Barquettes Chocolat Noisette - Belle France', 'JPHHod.png', 'https://www.myfitnesspal.com/food/calories/barquettes-chocolat-noisette-286616084')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'mibAFD.png', '[?25lhttps://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-au-chocolat/belle-france-sables-au-chocolat-au-lait-200g')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'GbdOJK.png', 'https://www.openculture.com/2021/07/a-gallery-of-1800-super-high-resolution-images-of-classic-paintings.html')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'DifAeB.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-au-chocolat/belle-france-sables-au-chocolat-au-lait-200g')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'mmDcdk.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-au-chocolat/belle-france-sables-au-chocolat-au-lait-200g')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'NaBMbM.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-au-chocolat/belle-france-sables-au-chocolat-au-lait-200g')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'FnpkGj.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-au-chocolat/belle-france-sables-au-chocolat-au-lait-200g')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'EgLmGO.png', '[?25lhttps://www.myfitnesspal.com/food/calories/sabl-s-coco-belle-france-sabl-coco-139620408')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'hgMFbL.png', 'https://www.myfitnesspal.com/food/calories/sabl-s-coco-belle-france-sabl-coco-139620408')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'hAAokM.png', 'https://www.myfitnesspal.com/food/calories/sabl-s-coco-belle-france-sabl-coco-139620408')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'iGOMeH.jpg', 'https://wallpapercave.com/16k-wallpapers')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'fPBnDN.jpg', 'https://world-gd.openfoodfacts.org/product/3258561020358/sabl%C3%A9s-coco-belle-france')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'JFeelF.png', 'https://wallpapercave.com/16k-wallpapers')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'EmEfJa.png', 'https://wallpapercave.com/16k-wallpapers')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'mPFBHI.png', 'https://wallpapercave.com/16k-wallpapers')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'DpIpnA.jpg', 'https://world-gd.openfoodfacts.org/product/3258561020358/sabl%C3%A9s-coco-belle-france')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'jjcEhM.jpg', 'https://world-fr.openfoodfacts.org/produit/3258561021171/sables-aux-cereales-chocolat-lait-belle-france')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'DleJjN.jpg', 'https://world-fr.openfoodfacts.org/produit/3258561021171/sables-aux-cereales-chocolat-lait-belle-france')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'MnhLnP.jpg', 'https://wallpapercave.com/16k-wallpapers')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'IAPPNI.jpg', 'https://world-gd.openfoodfacts.org/product/3258561020358/sabl%C3%A9s-coco-belle-france')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'lpGIja.webp', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-sables-aux-cereales-chocolat-lait-200g')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'ofDAgN.jpg', 'https://www.gettyimages.com/photos/gouter')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'kObBdo.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-sables-aux-cereales-chocolat-lait-200g')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'gEpLOo.jpg', 'https://www.gettyimages.com/photos/gouter')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'fKMAbA.jpg', 'https://www.gettyimages.com/photos/gouter')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'kAhPCJ.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-sables-aux-cereales-chocolat-lait-200g')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'hAaNIF.jpg', '[?25lhttps://world-th.openfoodfacts.org/product/3258561412948/torsades-%C3%A7-la-carbonara-belle-france')
insert into image (query, filename, site) values ('16 Gouters Carres Van. B. F - Belle France', 'nGnCaP.jpg', 'https://www.gettyimages.com/photos/gouter')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'oacEPD.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-sables-aux-cereales-chocolat-lait-200g')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'CKLEKj.jpg', 'https://world-th.openfoodfacts.org/product/3258561412948/torsades-%C3%A7-la-carbonara-belle-france')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'mBkKNl.png', 'https://www.lepetitdepot.com/fr/catalogue/epicerie-sucree/biscuits-et-gateaux-moelleux/belle-france-sables-aux-cereales-chocolat-lait-200g')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'FfAGgi.jpg', 'https://world-gd.openfoodfacts.org/product/3258561020358/sabl%C3%A9s-coco-belle-france')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'BNePLP.jpg', 'https://world-gd.openfoodfacts.org/product/3258561020358/sabl%C3%A9s-coco-belle-france')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'PlMOHK.jpg', 'https://www.lalaitiere.fr/recette/velours-de-creme-au-chocolat-au-lait-petits-sables-aux-cereales/')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'kJlcIj.jpg', 'https://www.awf.org/wildlife-conservation/sable')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'kEkgaI.jpg', 'https://world-th.openfoodfacts.org/product/3258561412948/torsades-%C3%A7-la-carbonara-belle-france')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'JDndOA.jpg', 'https://www.awf.org/wildlife-conservation/sable')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'BDbbFo.webp', 'https://www.awf.org/wildlife-conservation/sable')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'fKhcFI.jpg', 'https://world-th.openfoodfacts.org/product/3258561412948/torsades-%C3%A7-la-carbonara-belle-france')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'mJcnaN.jpg', 'https://www.awf.org/wildlife-conservation/sable')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'gHjMkB.jpg', 'https://www.awf.org/wildlife-conservation/sable')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'BDgLhF.png', 'https://www.lalaitiere.fr/recette/velours-de-creme-au-chocolat-au-lait-petits-sables-aux-cereales/')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'IhAgNf.jpg', 'https://world-oc.openfoodfacts.org/produit/3258561020273/torsades-dorees-125g-b-f-belle-france')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'PbDoeo.jpg', 'https://www.whowhatwear.com/coco-chanel-photos')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'jIDanm.jpg', 'https://world-oc.openfoodfacts.org/produit/3258561020273/torsades-dorees-125g-b-f-belle-france')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'DfFijk.png', '[?25lhttps://en.wikipedia.org/wiki/Petit-Beurre')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'pdLHJB.jpg', 'https://www.whowhatwear.com/coco-chanel-photos')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'pfaKGG.jpg', 'https://www.whowhatwear.com/coco-chanel-photos')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'ncfIEc.jpg', 'https://world.openfoodfacts.org/product/3258561020778/petit-beurre-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'IMHkDo.jpg', 'https://www.whowhatwear.com/coco-chanel-photos')
insert into image (query, filename, site) values ('Sablés Coco Belle France', 'ApDENG.jpg', 'https://www.whowhatwear.com/coco-chanel-photos')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'IndkNP.jpg', 'https://world-oc.openfoodfacts.org/produit/3258561020273/torsades-dorees-125g-b-f-belle-france')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'PgmHdC.jpg', 'https://world-oc.openfoodfacts.org/produit/3258561020273/torsades-dorees-125g-b-f-belle-france')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'ngahfB.jpg', '[?25lhttps://world.openfoodfacts.org/product/3222471110508/biscuits-fourres-noisette-casino')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'aBEBeO.jpg', 'https://world-oc.openfoodfacts.org/produit/3258561020273/torsades-dorees-125g-b-f-belle-france')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'ohDMNp.png', 'https://www.medicalnewstoday.com/articles/320619')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'OhJkjJ.jpg', 'https://world.openfoodfacts.org/product/3222471110508/biscuits-fourres-noisette-casino')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'mncchL.jpg', 'https://www.dreamstime.com/photos-images/torsades.html')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'cpFfhc.jpg', 'https://www.dreamstime.com/photos-images/torsades.html')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'edPPhP.jpg', 'https://www.dreamstime.com/photos-images/torsades.html')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'hKBmLn.jpg', 'https://world.openfoodfacts.org/product/3222471110508/biscuits-fourres-noisette-casino')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'joPMGp.jpg', 'https://world.openfoodfacts.org/product/3258561020778/petit-beurre-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'knhfha.jpg', 'https://www.shutterstock.com/search/sable')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'EPaMeh.jpg', 'https://www.shutterstock.com/search/sable')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'lcfAkf.jpg', 'https://www.shutterstock.com/search/sable')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'JJkFOi.jpg', 'https://www.shutterstock.com/search/sable')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'PNdEHa.jpg', 'https://www.dreamstime.com/photos-images/torsades.html')
insert into image (query, filename, site) values ('Torsades Dorees 125G B. F - Belle France', 'FHiIjM.jpg', 'https://www.dreamstime.com/photos-images/torsades.html')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'ccnMNH.jpg', 'https://www.shutterstock.com/search/sable')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'NjbmOm.jpg', 'https://www.istockphoto.com/photos/les-sables-dolonne')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'pLAFpD.jpg', 'https://world.openfoodfacts.org/product/3258561020778/petit-beurre-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'CIiKiC.jpg', 'https://www.valgourmand.com/6049-sables-fourres-chocolat-noisette-150g-bonne-maman-ref-sm607.html')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'lpbOpm.jpg', 'https://www.valgourmand.com/6049-sables-fourres-chocolat-noisette-150g-bonne-maman-ref-sm607.html')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'gMhmpN.jpg', 'https://world.openfoodfacts.org/product/3258561020778/petit-beurre-chocolat-au-lait-belle-france')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'JolIol.jpg', 'https://www.istockphoto.com/photos/beurre-photos')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'NgnjHo.jpg', 'https://www.valgourmand.com/6049-sables-fourres-chocolat-noisette-150g-bonne-maman-ref-sm607.html')
insert into image (query, filename, site) values ('Petit beurre - Belle France', 'FenHBd.jpg', 'https://www.istockphoto.com/photos/beurre-photos')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'Befjko.jpg', 'https://www.valgourmand.com/6049-sables-fourres-chocolat-noisette-150g-bonne-maman-ref-sm607.html')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'LJINCm.jpg', 'https://www.valgourmand.com/6049-sables-fourres-chocolat-noisette-150g-bonne-maman-ref-sm607.html')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'nCMOFg.jpg', 'https://www.ptitchef.com/recettes/autre/sables-fourres-aux-noisettes-fid-805831')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'OKLjEO.jpg', 'https://www.ptitchef.com/recettes/autre/sables-fourres-aux-noisettes-fid-805831')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'kOdmeB.jpg', 'https://www.ptitchef.com/recettes/autre/sables-fourres-aux-noisettes-fid-805831')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'bNjKbA.jpg', 'https://www.lalaitiere.fr/recette/velours-de-creme-au-chocolat-au-lait-petits-sables-aux-cereales/')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'jccBFA.jpg', 'https://www.labellevie.com/produit/42865/sables-les-p-tit-curieux-cereales-chocolat-au-lait-bio-bjorg-192-g')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'GECEao.jpg', 'https://www.ptitchef.com/recettes/autre/sables-fourres-aux-noisettes-fid-805831')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'bAhGMP.png', 'https://www.labellevie.com/produit/42865/sables-les-p-tit-curieux-cereales-chocolat-au-lait-bio-bjorg-192-g')
insert into image (query, filename, site) values ('Sables fourrés noisette - Belle France', 'dMNfGE.png', 'https://www.ptitchef.com/recettes/autre/sables-fourres-aux-noisettes-fid-805831')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'mHCHlb.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/biscuits-sables-aux-cereales-belle-france-chocolat-au-lait-195g-mrm00229/')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'nClMLm.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/biscuits-sables-aux-cereales-belle-france-chocolat-au-lait-195g-mrm00229/')
insert into image (query, filename, site) values ('Sablés aux céréales chocolat lait - Belle France', 'emIGAm.jpg', 'https://www.sodishop.com/shop/supermarche/alimentaire/biscuits-sables-aux-cereales-belle-france-chocolat-au-lait-195g-mrm00229/')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'CjaJHf.jpg', '[?25lhttps://www.labellevie.com/produit/49984/gaufrettes-fourrees-praline-noisette-u-110-g')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'EcpAca.png', 'https://www.labellevie.com/produit/49984/gaufrettes-fourrees-praline-noisette-u-110-g')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'FHJGfg.png', 'https://photos.google.com/')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'dNdeja.png', 'https://photos.google.com/')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'lblpag.jpg', 'https://photos.google.com/')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'leBCId.jpg', 'https://photos.google.com/')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'BoBeME.jpg', 'https://photos.google.com/')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'hhoGJe.jpg', 'https://fr.openfoodfacts.org/produit/3258561019161/gaufrettes-a-la-noisette-belle-france')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'cAPhAA.jpg', 'https://fr.openfoodfacts.org/produit/3258561019161/gaufrettes-a-la-noisette-belle-france')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'HMKhAC.jpg', 'https://fr.openfoodfacts.org/produit/3258561019161/gaufrettes-a-la-noisette-belle-france')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'oNimBh.png', 'https://www.loacker.com/ca/fr/produits/planete-gaufrettes/classic-noisette')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'dNikdF.png', 'https://www.loacker.com/ca/fr/produits/planete-gaufrettes/classic-noisette')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'JjnDcD.jpg', 'https://www.loacker.com/ca/fr/produits/planete-gaufrettes/classic-noisette')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'omipJc.png', 'https://www.loacker.com/ca/fr/produits/planete-gaufrettes/classic-noisette')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'CBbAdf.jpg', 'https://www.loacker.com/ca/fr/produits/planete-gaufrettes/classic-noisette')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'KdmgDh.jpg', 'https://www.gettyimages.com/photos/la-belle')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'mMJndm.jpg', 'https://www.gettyimages.com/photos/la-belle')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'jgBogL.jpg', 'https://www.gettyimages.com/photos/la-belle')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'hCLGGp.jpg', 'https://world.openfoodfacts.org/product/3258561019161/gaufrettes-a-la-noisette-belle-france')
insert into image (query, filename, site) values ('Gaufrettes À La Noisette - Belle France', 'kOpCPI.png', 'https://www.myfitnesspal.com/food/calories/gaufrettes-a-la-noisette-158626836')
